#!/usr/bin/env bash


set -e	#	exit if any command fails
set -u	#	Error on usage of unset variables
set -o pipefail


CORES=40 #number of cores to use for blast searches
KMERSIZE=31 # RD:61


hawkDir=/home/jake/HAWK-0.9.8-beta
#	My version, 2.2.4 never completed?
jellyfishDir=${hawkDir}/supplements/jellyfish-Hawk/bin	# the included version is modified 1.1.6
#jellyfishDir=/usr/bin
#sortDir=/usr/bin # my normal version seems to be the parallel version


#for file in $( ls -d /raid/data/raw/CCLS/bam/*bam )
for file in $( ls /raid/data/raw/CCLS/bam/{GM_,}{983899,63185,268325,439338,634370}.recaled.bam )
do
	OUTPREFIX=$( basename $file	.recaled.bam )


	if [ ${OUTPREFIX} == "120207" ] ; then
		echo "Skipping"
		continue
	fi


	f=${OUTPREFIX}_kmers_jellyfish
	if [ -f $f ] && [ ! -w $f ] ; then
		echo "Write-protected $f exists. Skipping."
	else
		echo "Creating $f"

		mkdir ${OUTPREFIX}_kmers

		${jellyfishDir}/jellyfish count -C -o ${OUTPREFIX}_kmers/tmp -m ${KMERSIZE} -t ${CORES} -s 5G <( samtools fastq $file )

		COUNT=$(ls ${OUTPREFIX}_kmers/tmp* |wc -l)

		if [ $COUNT -eq 1 ]
		then
 			mv ${OUTPREFIX}_kmers/tmp_0 ${f}
		else
			${jellyfishDir}/jellyfish merge -o ${f} ${OUTPREFIX}_kmers/tmp*
		fi
		rm -rf ${OUTPREFIX}_kmers

		chmod a-w $f
	fi

	f=${OUTPREFIX}.kmers.jellyfish.hist.csv
	if [ -f $f ] && [ ! -w $f ] ; then
		echo "Write-protected $f exists. Skipping."
	else
		echo "Creating $f"
		${jellyfishDir}/jellyfish histo -f -o ${f} -t ${CORES} ${OUTPREFIX}_kmers_jellyfish
		chmod a-w $f
	fi

	f=${OUTPREFIX}.kmers.hist.csv
	if [ -f $f ] && [ ! -w $f ] ; then
		echo "Write-protected $f exists. Skipping."
	else
		echo "Creating $f"
		#	swap, for some reason
		awk '{print $2"\t"$1}' ${OUTPREFIX}.kmers.jellyfish.hist.csv > ${f}
		chmod a-w $f
	fi


	f=${OUTPREFIX}_total_kmer_counts.txt
	if [ -f $f ] && [ ! -w $f ] ; then
		echo "Write-protected $f exists. Skipping."
	else
		echo "Creating $f"
		awk -f ${hawkDir}/countTotalKmer.awk ${OUTPREFIX}.kmers.hist.csv > ${f}
#		awk -f ${hawkDir}/countTotalKmer.awk ${OUTPREFIX}.kmers.hist.csv >> total_kmer_counts.txt
		chmod a-w $f
	fi


	f=${OUTPREFIX}_kmers.txt
	if [ -f $f ] && [ ! -w $f ] ; then
		echo "Write-protected $f exists. Skipping."
	else
		echo "Creating $f"
		${jellyfishDir}/jellyfish dump -c -L 2 ${OUTPREFIX}_kmers_jellyfish > ${f}
		chmod a-w $f
	fi

	f=${OUTPREFIX}_kmers_sorted.txt
	if [ -f $f ] && [ ! -w $f ] ; then
		echo "Write-protected $f exists. Skipping."
	else
		echo "Creating $f"
		sort --parallel=${CORES} -n -k 1 ${OUTPREFIX}_kmers.txt > ${f}
		chmod a-w $f
	fi
	
#		rm ${OUTPREFIX}_kmers_jellyfish	
#		rm ${OUTPREFIX}_kmers.txt		
			
#		echo "${OUTPREFIX}_kmers_sorted.txt" >> sorted_files.txt
		
done
