#!/usr/bin/env bash


set -e	#	exit if any command fails
set -u	#	Error on usage of unset variables
set -o pipefail


hawkDir=/home/jake/HAWK-0.9.8-beta

#	included version doesn't run. "missing libgsl.so.0". Won't compile. "baseprog recipe failed"
#eigenstratDir=${hawkDir}/supplements/EIG6.0.1-Hawk/bin
#	Using "apt install eigensoft"
eigenstratDir=/usr/bin
isDiploid=1



#	my mods moved from countKmers script
cat *_total_kmer_counts.txt > total_kmer_counts.txt
ls -1 *_kmers_sorted.txt > sorted_files.txt


noInd=$(cat sorted_files.txt | wc -l)


#	split gwas_info / total_kmer_counts.txt / sorted_files.txt into case/control files
$hawkDir/preProcess


cat case_total_kmers.txt control_total_kmers.txt > gwas_eigenstratX.total
cat 'case.ind' control.ind > gwas_eigenstratX.ind

caseCount=$(cat case_sorted_files.txt | wc -l)
controlCount=$(cat control_sorted_files.txt | wc -l)


#	This can take a while
$hawkDir/hawk $caseCount $controlCount


if [ "$isDiploid" == "0" ]; then
	$eigenstratDir/smartpca -V -p $hawkDir/parfile.txt > log_eigen.txt
else
	$eigenstratDir/smartpca -p $hawkDir/parfile.txt > log_eigen.txt
fi


$eigenstratDir/evec2pca.perl 10 gwas_eigenstrat.evec gwas_eigenstratX.ind gwas_eigenstrat.pca

tail -${noInd} gwas_eigenstrat.pca > pcs.evec

sort -g  -k 4 -t $'\t' case_out_w_bonf.kmerDiff > case_out_w_bonf_sorted.kmerDiff
head -200000 case_out_w_bonf_sorted.kmerDiff > case_out_w_bonf_top.kmerDiff

sort -g  -k 4 -t $'\t' control_out_w_bonf.kmerDiff > control_out_w_bonf_sorted.kmerDiff
head -200000 control_out_w_bonf_sorted.kmerDiff > control_out_w_bonf_top.kmerDiff

Rscript $hawkDir/log_reg_case.R
Rscript $hawkDir/log_reg_control.R

paste pvals_case_top.txt case_ut_w_bonf_top.kmerDiff  > pvals_case_top_merged.txt
sort -g -k 1 -t $'\t' pvals_case_top_merged.txt > pvals_case_top_merged_sorted.txt 

paste pvals_control_top.txt control_out_w_bonf_top.kmerDiff  > pvals_control_top_merged.txt
sort -g -k 1 -t $'\t' pvals_control_top_merged.txt > pvals_control_top_merged_sorted.txt

$hawkDir/convertToFasta    

#rm case_out_w_bonf.kmerDiff
#rm case_out_wo_bonf.kmerDiff
#rm control_out_w_bonf.kmerDiff
#rm control_out_wo_bonf.kmerDiff        

